### ISSUE TITLE
commands does not working as expected

### ISSUE THREAD

**Issue by surjit** [qwefgh90/ng-terminal#11]
Hi,

How to get it working with actual terminal e.g live linux commands and output on Ubuntu

Thanks,

**Comment by qwefgh90** [comment]
Hello :)

As you know, ng-terminal is web terminal emulator working based on xterm. It is a simple library only having a presentation layer.

So if you want to run linux shell on ng-terminal, you need a linux machine where you should develop a simple websocket server which a browser can connect to. And you make a web server to internally communicate with a bash process via a library for pty like [node-pty](https://github.com/microsoft/node-pty).

Finally, ng-terminal have a simple role to show data sent from websocket or send data to the server via websocket.

Thanks
