### ISSUE TITLE
NgTerminal in mat-tab

### ISSUE THREAD

**Issue by gucci-quoci** [qwefgh90/ng-terminal#15]
Hey, I want to use your NgTerminal in a mat-tab. But somehow it doesn't work and I get [this error](https://imgur.com/gallery/wPABilU). If I don't use a tab it works fine. Can you help me?
```
<ng-container *ngIf="(asyncTabs | async) === null">
  Loading tabs...
</ng-container>

<mat-tab-group>
  <mat-tab>
    <ng-template mat-tab-label>Tab1</ng-template>
  </mat-tab>
  <mat-tab>
    <ng-template mat-tab-label>Tab2</ng-template>
    <ng-terminal></ng-terminal>
  </mat-tab>
</mat-tab-group>
```

**Comment by qwefgh90** [comment]
It seems to take few days to handle this bug. Although an option of `fixedGrid` makes the bug disappear, I think it may not work completely.

Maybe you can achieve what you want by using `(selectedTabChange)` which is a event emitter of the tab component with manipulating and changing one div element  like `<div>{{tabNumber}}content</div>`. It would be not a easy way.

**Comment by qwefgh90** [comment]
I make changes which are tested in [a new spec](https://github.com/qwefgh90/ng-terminal/blob/master/projects/ng-terminal/src/lib/ng-terminal.component.material.spec.ts). Now you can use `<ng-terminal>` wrapped by `<div>` in `<mat-tab>`. Please try it.
