### ISSUE TITLE
Could you please expose removeBorder as part of NgTerminal interface?

### ISSUE THREAD

**Issue by lwang16** [qwefgh90/ng-terminal#17]
I have tried to create a wrapper div and force "border: unset ! important" on my angular 8 project and it doesn't work. Could you please make removeBorder public by adding it to NgTerminal interface?

**Comment by qwefgh90** [comment]
I've just added setStyle() which takes key-value styles object in latest version. It helps to give the terminal component custom styles. Please see an example https://github.com/qwefgh90/ng-terminal/blob/master/src/app/example.component.ts#L85

**Comment by lwang16** [comment]
Thank you for the quick update!
