### ISSUE TITLE
Dimensions aren't set debug log

### ISSUE THREAD

**Issue by luvies** [qwefgh90/ng-terminal#50]
I'm getting an issue where, when in the background, [this](https://github.com/qwefgh90/ng-terminal/blob/v3.0.0-alpha/projects/ng-terminal/src/lib/ng-terminal.component.ts#L129) debug log gets prints many times a second. Once the component is in the foreground, it works fine.

Because the debug log is printed quite often, it can clutter up the console, and in production builds, it can end up being printed thousands of times in a minute or 2.

**Comment by qwefgh90** [comment]
I'm sorry to reply late. Thanks. It has been removed.
