### ISSUE TITLE
can't change color for different lines, just have option to change whole theme.

### ISSUE THREAD

**Issue by sobhardwaj** [qwefgh90/ng-terminal#53]
I want to change colors in different lines. any suggestions ??

**Comment by qwefgh90** [comment]
I have found character attributes to change colors of next inputs in [the link](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_)
But maybe it isn't that useful to change colors in different lines. And in original project xterm I can't find that features.
It could take times to find control sequences/options to change colors in different lines.
