### ISSUE TITLE
dynamic terminal

### ISSUE THREAD

**Issue by weihangChen** [qwefgh90/ng-terminal#55]
### context and goal

I use the `ng terminal` component to connect to different docker host machine; and at the start there is no terminal shown because user did not run any docker job on docker host machine yet. What happens is that every time user creates a new docker job on a new docker machine then I create a new `ng-terminal` for the new host machine and let user switch between these terminals.

## problem

I am not good at Angular, the way of using this component is decorative, at the moment I have managed to create a list of terminal at the html page by using a array
```
<div #terminalWrapper class="terminal-wrapper">
    <ng-terminal *ngFor="let x of jobSocketCache" id={{x[0]}} class="terminal"></ng-terminal>
</div> 
```
but I need to reach the `terminal` object in typescript, without using `viewchild` i have no idea how to do it in a programmatic way. Please help

**Comment by qwefgh90** [comment]
Did you solve this problem?
I found how to access template variable list. See below.
https://stackoverflow.com/questions/48347854/how-to-set-unique-template-reference-variables-inside-an-ngfor-angular
If you didn't try this yet, please try following codes.
#### x.component.html
```html
<div *ngFor="let i of multiple">
<ng-terminal #test></ng-terminal>
<div>break</div>
</div>
```
#### x.component.ts
```typescript
@ViewChildren('test') terminalList: QueryList<NgTerminal>;
```
