### ISSUE TITLE
Scrolling the entire page when scrolling with the mouse in the terminal

### ISSUE THREAD

**Issue by Jebati** [qwefgh90/ng-terminal#56]

**Comment by qwefgh90** [comment]
I can reproduce this bug only when xtermjs is initialized in Angular not the vanilla env. I will keep track of this issue.

**Comment by qwefgh90** [comment]
This issue is resolved at [v3.2.0](https://github.com/qwefgh90/ng-terminal/releases/tag/untagged-803ce21a75f6af974e74).
