### ISSUE TITLE
Can we have the xtermjs lib kepts up to date?

### ISSUE THREAD

**Issue by AntonyChiossi** [qwefgh90/ng-terminal#59]
Hi @qwefgh90, the xtermjs are very effective at resolving bugs, they do it very quickly.

Can you update le xtermjs version to latest (4.14.1)?

thank you!

**Comment by qwefgh90** [comment]
Thank you. I will do it as soon as possible.

**Comment by qwefgh90** [comment]
I just have updated xtermjs version to latest.
https://github.com/qwefgh90/ng-terminal/releases/tag/v3.1.1
Thank you.
