### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by Clashsoft** [qwefgh90/ng-terminal#60]
Please update the library to use Angular 13. While still compatible, the package format has significantly changed, primarily due to use of Ivy and the removed need for ngcc.

**Comment by qwefgh90** [comment]
I think so. I have been working on upgrading Angular to the higher version(it was 11). I will release newer version in a couple of days.

**Comment by qwefgh90** [comment]
I released [4.0.0-alpha.2](https://www.npmjs.com/package/ng-terminal) which works with **Angular 13** well. And I am working on improving some minor bugs.
If you have any problem, let me know it. Thank you.

**Comment by Clashsoft** [comment]
I think there is a minor issue with Ivy, the library still triggers ngcc. Also, it uses an older version of angular-resizable-element, which has the same problem.

**Comment by qwefgh90** [comment]
Sorry for slow progress on this issue. I wasn't familiar with Ivy. So i am learning Angular ivy feature.

I will decide to forgive backward compatibility for View Engine apps by enabling partial mode soon. 
![image](https://user-images.githubusercontent.com/7572251/151683803-8c51d1d6-2aa6-46a1-872d-620cdca61f10.png)

**Comment by qwefgh90** [comment]
I believe new release resolved this issue in https://github.com/qwefgh90/ng-terminal/releases/tag/v5.0.0-beta.2
I updated the angular-resizable-element version in package.json made the ivy library distribution. :)

**Comment by elgurinn** [comment]
Will there be a stable version released?

**Comment by qwefgh90** [comment]
@elgurinn There will not be much changes in the stable version. Is there any problem in the latest version?
