### ISSUE TITLE
Fix resize bug by updating xterm-addon-fit

### ISSUE THREAD

**Issue by z0rb** [qwefgh90/ng-terminal#72]
Hi,

I had issues resizing the terminal after updating ng-terminal to the latest version. After a long while I found the bug responsible for it: https://github.com/xtermjs/xterm.js/issues/4344

After updating xterm-addon-fit to 0.7.0,  ng-terminal resized properly again. Can you upgrade the dependency so everyone gets the fix?

**Comment by qwefgh90** [comment]
Hello. 

Thank you for letting me know the issue. I made a [commit](https://github.com/qwefgh90/ng-terminal/commit/a2b9efa2800652840e55a7541c350b9e8e552b12) to bump up the xterm-addon-fit version to 0.7.0 and published new release 5.5.0. 

I'm not sure new release's working well. 
If you need any support, please make a comment.

**Comment by z0rb** [comment]
Thanks! I removed the dependency override and tested with the new version, all good.
