### ISSUE TITLE
Wrong size when element is rendered

### ISSUE THREAD

**Issue by AntonyChiossi** [qwefgh90/ng-terminal#77]
Hi, I am experiencing this bug.

I tried, with intersection observer or a timeout, to render the component after a while and it seems to fix the issue.

Bug:
![image](https://github.com/qwefgh90/ng-terminal/assets/107461170/76d23033-09ea-4c34-87f5-25011e6aa56a)
![image](https://github.com/qwefgh90/ng-terminal/assets/107461170/e0e65d60-42c3-4820-bef2-9ab8a20ad9c0)

Expected:
![image](https://github.com/qwefgh90/ng-terminal/assets/107461170/90057d25-e32e-402d-932b-091240036e58)
![image](https://github.com/qwefgh90/ng-terminal/assets/107461170/a0025c8e-c034-42de-9697-7205feed7b3b)

### Angular version: 16.2.0

**Comment by kashyapExt** [comment]
Is there anyway to occupy the full screen when we navigate to ng-terminal component? right now it is only taking upto 60% of height.

**Comment by qwefgh90** [comment]
@AntonyChiossi 
Could you let me know which library you used for creating tabs that contain the ng-terminal component?

**Comment by qwefgh90** [comment]
Hi! @kashyapExt 
The width and height of ng-terminal component depends on the size of parent element. 
Could you create a different issue and explain your current layout that contains ng-terminal briefly?
Thanks.

**Comment by AntonyChiossi** [comment]
@qwefgh90 I'm using [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap)
