### ISSUE TITLE
Angular 17 compatibility

### ISSUE THREAD

**Issue by rustedredswitch** [qwefgh90/ng-terminal#81]
Hello, I want to use your project in my Angular app but I have problems of compatibility with _@angular/common@17.0.7_.
When will it be possible to use **ng-terminal** with Angular 17?
Thanks,
Alessandro

**Comment by qwefgh90** [comment]
Hello,
I tried to modify the support version simply, however, I found that the methods for importing Module and Component libraries have slightly changed in Angular 17. I will check out new features of Angular 17 and then I will start the migration as soon as possible.

**Comment by rustedredswitch** [comment]
Thanks for your answer.
Have nice holidays 🎄
